apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-metrics-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-metrics-app
  template:
    metadata:
      labels:
        app: python-metrics-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: python-metrics-app:latest   # Vamos carregar a imagem local
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"